name: bayes-beat
channels:
  - conda-forge
dependencies:
  - numpy<2.0
  - pytorch-cpu
  - nessai
  - pycondor
  - hdf5storage
  - h5py
  - corner
  - dill
  - numba
  - click
  - seaborn
  - sympy
  - nbconvert
  - jupyter-book
  - pip
  - pip:
      - bayesbeat
