# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Bayesian Inference for Diagnosing Issues in Measurements of Disk Resonators
author: Michael J. Williams, Simon C. Tait, Joseph Bayley, Bryan Bar

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Only build the table of contents files
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mj-will/bayesbeat-paper  # Online location of your book
  path_to_book: docs 
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
